6
Traceback (most recent call last):
  File "/n/home05/smadan/.conda/envs/domain_adaptation/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/n/home05/smadan/.conda/envs/domain_adaptation/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/net/coxfs01/srv/export/coxfs01/pfister_lab2/share_root/Lab/spandan/contextual_domain_adaptation/DomainBed/domainbed/scripts/train.py", line 65, in <module>
    with open(args_read_file,'r') as F:
FileNotFoundError: [Errno 2] No such file or directory: 'dg_all_envs/SagNet/out_continued_2.txt'
Continue training, so reading seed...
