6
Warning: You are running the empty baseline, so network is being fed an input of just zeros.
annotations: ../openrooms/annotation_files/train_main_xml_50_lights_v3.json
batch_size: 200
blur_context: 125
blur_target: 0
checkpoint: checkpoint_20.tar
cnn_baseline: false
empty_baseline: false
git: 2179780af36e53218cf9f25623959fb36ae2379d
imagedir: ../
imbalance_reweighting: false
learning_rate: 1.0e-05
lift_the_flap: false
no_context: false
num_classes: 13
num_decoder_heads: 8
num_decoder_layers: 6
test_annotations: ../openrooms/annotation_files/train_main_xml_50_lights_test_v3.json
test_imagedir: ../
uncertainty_gate_type: learned
uncertainty_threshold: 0.8
weighted_prediction: true

Initializing model from checkpoint checkpoint_20.tar
Traceback (most recent call last):
  File "test.py", line 276, in <module>
    checkpoint = torch.load(args.checkpoint, map_location="cpu")
  File "/n/home05/smadan/.conda/envs/domain_adaptation/lib/python3.8/site-packages/torch/serialization.py", line 771, in load
    with _open_file_like(f, 'rb') as opened_file:
  File "/n/home05/smadan/.conda/envs/domain_adaptation/lib/python3.8/site-packages/torch/serialization.py", line 270, in _open_file_like
    return _open_file(name_or_buffer, mode)
  File "/n/home05/smadan/.conda/envs/domain_adaptation/lib/python3.8/site-packages/torch/serialization.py", line 251, in __init__
    super(_open_file, self).__init__(open(name, mode))
FileNotFoundError: [Errno 2] No such file or directory: 'v3_output/4_style_hotswapped_lights_blur_context_125/checkpoint_20.tar'
