3
Warning: You are running the empty baseline, so network is being fed an input of just zeros.
annotations: ../openrooms/annotation_files/train_main_xml_50_lights_v3.json
batch_size: 200
checkpoint: checkpoint_11.tar
empty_baseline: false
git: e22ff54d4e15e859ff3672c5fc808cec0abfc80d
imagedir: ../
imbalance_reweighting: false
learning_rate: 1.0e-05
lift_the_flap: false
no_context: false
num_classes: 13
num_decoder_heads: 8
num_decoder_layers: 6
test_annotations: ../openrooms/annotation_files/train_main_xml_50_lights_test_v3.json
test_imagedir: ../
uncertainty_gate_type: learned
uncertainty_threshold: 0.8
weighted_prediction: true

Initializing model from checkpoint checkpoint_11.tar
Traceback (most recent call last):
  File "test.py", line 163, in <module>
    checkpoint = torch.load(args.checkpoint, map_location="cpu")
  File "/n/home05/smadan/.conda/envs/domain_adaptation/lib/python3.8/site-packages/torch/serialization.py", line 594, in load
    with _open_file_like(f, 'rb') as opened_file:
  File "/n/home05/smadan/.conda/envs/domain_adaptation/lib/python3.8/site-packages/torch/serialization.py", line 230, in _open_file_like
    return _open_file(name_or_buffer, mode)
  File "/n/home05/smadan/.conda/envs/domain_adaptation/lib/python3.8/site-packages/torch/serialization.py", line 211, in __init__
    super(_open_file, self).__init__(open(name, mode))
FileNotFoundError: [Errno 2] No such file or directory: 'v3_output/three_hotswapped_light_50/checkpoint_11.tar'
